//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlePatrimonios
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.bens = new HashSet<ben>();
        }
    
        public int idCategoria { get; set; }
        public string descCategoria { get; set; }
    
        public virtual ICollection<ben> bens { get; set; }
    }
}
