//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlePatrimonios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class controle_patrimonialEntities : DbContext
    {
        public controle_patrimonialEntities()
            : base("name=controle_patrimonialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ben> bens { get; set; }
        public DbSet<categoria> categorias { get; set; }
        public DbSet<patrimonio> patrimonios { get; set; }
        public DbSet<predio> predios { get; set; }
        public DbSet<sala> salas { get; set; }
    }
}
