//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlePatrimonios
{
    using System;
    using System.Collections.Generic;
    
    public partial class patrimonio
    {
        public int idPatrimonio { get; set; }
        public string numPatrimonio { get; set; }
        public int idBem { get; set; }
        public int idCategoria { get; set; }
        public int idSala { get; set; }
        public int idPredio { get; set; }
    
        public virtual ben ben { get; set; }
        public virtual sala sala { get; set; }
    }
}
