//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlePatrimonios
{
    using System;
    using System.Collections.Generic;
    
    public partial class predio
    {
        public predio()
        {
            this.salas = new HashSet<sala>();
        }
    
        public int idPredio { get; set; }
        public string descPredio { get; set; }
    
        public virtual ICollection<sala> salas { get; set; }
    }
}
