//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlePatrimonios
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala
    {
        public sala()
        {
            this.patrimonios = new HashSet<patrimonio>();
        }
    
        public int idSala { get; set; }
        public string descSala { get; set; }
        public int idPredio { get; set; }
    
        public virtual ICollection<patrimonio> patrimonios { get; set; }
        public virtual predio predio { get; set; }
    }
}
